package(default_visibility = ["//visibility:public"])

cc_library(
    name = "color",
    srcs = ["color.cc"],
    hdrs = ["color.h"],
    deps = [
        "@ncurses//:ncurses_headers",
        "@ncurses",
    ],
)
